### PR TITLE
Update resin to balena

### PR DESCRIPTION
**Pull request by pcgeek86**

### CODE REVIEW

**Comment by zrzka** [comment]
You sure about the _Inc._? For example just released Etcher 1.5.0 contains _Balena Ltd_ (see about).

**Comment by zrzka** [comment]
Tried to search GH ...

* [Balena Ltd](https://github.com/search?q=%22Balena+Ltd%22&type=Code) gives 179+ results
* [Balena Inc](https://github.com/search?q=%22Balena+Inc%22&type=Code) gives just 8 results

**Comment by pcgeek86** [comment]
@zrzka That's a good point, but the Balena HQ in the United States is formally Balena Inc. It's a corporation registered in the State of Delaware, and licensed to do business in the State of Washington. In this case, I don't think that the numbers necessarily tell the full story.

You can search the Delaware business entities here: https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx

Also, Balena Inc. appears on our Master Agreement here: https://www.balena.io/master-agreement/

**Comment by alisondavis17** [comment]
@pcgeek86 @zrzka Balena Inc. is the legal name of our US Company, Balena Ltd is the legal name of the UK Parent Company. So you're both correct in a sense :)

**Comment by alisondavis17** [comment]
Copyrights, however, should be under Balena Ltd, the parent company. Not sure why this project has or needs one though.

**Comment by pcgeek86** [comment]
Changed back to Ltd.

**Pull request merged**
